#!/usr/bin/env python3
"""Regenerate everything derived from `assets/logo.svg`.

Layout: `assets/` holds the source SVG, the generation scripts, and a
`generated/` subdirectory with the committed desktop derivatives — the
canonical source of derivative bytes. The platform copies under
`frontend/` and `src-tauri/` are populated by the copy step at the bottom
of this script, so a fresh clone always has usable icons, even on
machines without imagemagick.

Generation breaks into two stages:

  Stage 1 — refresh `assets/generated/*` from `assets/logo.svg`:
    Text derivatives (Python text emission, always runs):
      - qxpLogoPath.ts           TS path constants
      - icon.svg                 favicon SVG (with gradient defs)
    Bitmap derivative (imagemagick — conditional on `magick` or
    `nix-shell` being reachable, so cloners without imagemagick still
    succeed and just keep the committed PNG):
      - desktop-icon.png         1024x1024 RGBA (Tauri requires alpha)

  Stage 2 — copy `assets/generated/*` into the platform paths:
      - frontend/src/lib/qxpLogoPath.ts
      - frontend/public/icon.svg
      - src-tauri/icons/icon.png

Run whenever logo.svg changes; commit the resulting diff.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "assets/logo.svg"
RENDER = ROOT / "assets/scripts/render.sh"

# Canonical committed location for generated bytes.
GEN = ROOT / "assets/generated"
GEN_TS = GEN / "qxpLogoPath.ts"
GEN_FAVICON = GEN / "icon.svg"
GEN_DESKTOP_PNG = GEN / "desktop-icon.png"

# Platform locations — copies of the canonical files above.
DST_TS = ROOT / "frontend/src/lib/qxpLogoPath.ts"
DST_FAVICON = ROOT / "frontend/public/icon.svg"
DST_PNG = ROOT / "src-tauri/icons/icon.png"

# Brand gradient (vertical, top -> bottom). Mirror `assets/scripts/render.sh`
# when changing — it bakes the same values into the Tauri PNG.
GRAD_TOP = "#00FF9D"
GRAD_BOTTOM = "#22CCAA"


def parse_viewbox(svg: str) -> float:
    m = re.search(r'viewBox="([\d.\s-]+)"', svg)
    if not m:
        sys.exit("logo.svg: no viewBox")
    vals = [float(v) for v in m.group(1).split()]
    if len(vals) != 4 or vals[2] != vals[3]:
        sys.exit(f"logo.svg: non-square viewBox {vals}")
    return vals[2]


def first_path_d(svg: str) -> str:
    """Return the `d` attribute of the first `<path>` in the SVG. The `\\b`
    before `d` keeps the match off `id="..."`."""
    m = re.search(r'<path\b[^>]*?\bd="([^"]+)"', svg, re.DOTALL)
    if not m:
        sys.exit("logo.svg: no <path> element found")
    return m.group(1)


def strip_viewbox_rect(d: str) -> str:
    """Return the SVG path `d` with the leading viewBox-sized rect subpath
    removed. The source SVG packs two subpaths into one `<path>`:
        m0 0h<vb>v<vb>h-<vb>v-<vb>z   <logo subpath>
    The first 'z' (case-insensitive) ends the rect; everything after is the
    logo. Preserves the original compact relative-command form so the
    generated TS/SVG strings match what a hand-authored desktop file would
    contain."""
    for i, c in enumerate(d):
        if c in "zZ":
            return d[i + 1:].lstrip()
    return d


def emit_ts(vb: float, logo_d: str) -> str:
    return (
        "// Auto-generated by assets/scripts/generate-logo.py from assets/logo.svg.\n"
        "// Do not edit by hand — rerun `assets/scripts/generate-logo.py` to refresh.\n"
        "//\n"
        "// Single source of truth for the qxp logomark's SVG path data. Used by both\n"
        "// the on-screen Logo component and the favicon-generation pipeline in\n"
        "// `lib/notifications/notifications.ts`.\n"
        "\n"
        f"export const QXP_LOGO_VIEWBOX = '0 0 {int(vb)} {int(vb)}';\n"
        f"export const QXP_LOGO_VIEWBOX_SIZE = {int(vb)};\n"
        f"export const QXP_LOGO_PATH_D =\n"
        f"  '{logo_d}';\n"
    )


def emit_favicon_svg(vb: float, logo_d: str) -> str:
    return (
        "<!-- Auto-generated by assets/scripts/generate-logo.py from assets/logo.svg. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {int(vb)} {int(vb)}">\n'
        '  <defs>\n'
        '    <linearGradient id="qxp-logo-grad" x1="0" y1="0" x2="0" y2="1">\n'
        f'      <stop offset="0%" stop-color="{GRAD_TOP}"/>\n'
        f'      <stop offset="100%" stop-color="{GRAD_BOTTOM}"/>\n'
        '    </linearGradient>\n'
        '  </defs>\n'
        f'  <path fill="url(#qxp-logo-grad)" d="{logo_d}"/>\n'
        '</svg>\n'
    )


def install(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst)
    print(f"installed {dst.relative_to(ROOT)}")


def main() -> None:
    svg = SRC.read_text()
    vb = parse_viewbox(svg)
    # The desktop derivatives operate on the original path's logo subpath
    # (viewBox rect stripped), in its compact relative form, so the TS
    # string and the favicon SVG match a hand-authored desktop file.
    logo_d = strip_viewbox_rect(first_path_d(svg))

    GEN.mkdir(parents=True, exist_ok=True)

    # === Stage 1a: text derivatives -> assets/generated/ ===
    # Pure-Python text emission, always runs.
    GEN_TS.write_text(emit_ts(vb, logo_d))
    print(f"wrote {GEN_TS.relative_to(ROOT)}")

    GEN_FAVICON.write_text(emit_favicon_svg(vb, logo_d))
    print(f"wrote {GEN_FAVICON.relative_to(ROOT)}")

    # === Stage 1b: PNG derivative -> assets/generated/ ===
    # Conditional on imagemagick. Two reachability paths:
    #   - `magick` directly on PATH (e.g. `brew install imagemagick` on
    #     macOS). Invoke render.sh through bash so its nix-shell shebang
    #     is bypassed and the already-present `magick` is used.
    #   - `nix-shell` on PATH. Invoke render.sh directly so its own
    #     shebang fires and provisions imagemagick.
    # If neither is present, skip — the PNG in assets/generated/ is
    # committed, so Stage 2 below still copies usable bytes into the
    # platform path.
    if shutil.which("magick"):
        subprocess.run(["bash", str(RENDER)], check=True)
    elif shutil.which("nix-shell"):
        subprocess.run([str(RENDER)], check=True)
    else:
        print("note: skipping PNG regen (neither `magick` nor `nix-shell` on PATH; committed PNG in assets/generated/ is used)")

    # === Stage 2: copy assets/generated/* -> platform paths ===
    # Always runs, regardless of which Stage-1 paths fired. This is what
    # makes a fresh clone build without any tooling — everything it needs
    # is already in assets/, just not yet at the paths the desktop build
    # expects.
    install(GEN_TS, DST_TS)
    install(GEN_FAVICON, DST_FAVICON)
    install(GEN_DESKTOP_PNG, DST_PNG)


if __name__ == "__main__":
    main()
