// Curated emoji list — about 230 entries grouped into 6 categories. Far from
// exhaustive (Unicode currently has ~3700) but covers the everyday set
// without the bundle hit of a full CLDR JSON. Phase 23 polish can swap this
// for a generated table if needed.

export type Emoji = {
  /** Emoji codepoint(s). */
  c: string;
  /** Search keywords (lowercase, space-separated). */
  k: string;
  /** Category. */
  cat: Category;
};

export type Category =
  | 'smileys'
  | 'people'
  | 'nature'
  | 'food'
  | 'activity'
  | 'travel'
  | 'objects'
  | 'symbols';

export const CATEGORY_LABELS: Record<Category, string> = {
  smileys: 'Smileys',
  people: 'People',
  nature: 'Nature',
  food: 'Food',
  activity: 'Activity',
  travel: 'Travel',
  objects: 'Objects',
  symbols: 'Symbols',
};

export const QUICK_REACTIONS = ['👍', '👎', '❤️', '😂', '😮', '😢', '🙏'];

// prettier-ignore
export const EMOJI: Emoji[] = [
  // smileys
  { c: '😀', k: 'grinning happy smile face', cat: 'smileys' },
  { c: '😃', k: 'smiley happy big eyes', cat: 'smileys' },
  { c: '😄', k: 'smile happy laugh', cat: 'smileys' },
  { c: '😁', k: 'beaming smile', cat: 'smileys' },
  { c: '😆', k: 'laughing satisfied', cat: 'smileys' },
  { c: '😅', k: 'sweat smile', cat: 'smileys' },
  { c: '😂', k: 'joy laugh tears', cat: 'smileys' },
  { c: '🤣', k: 'rofl rolling floor', cat: 'smileys' },
  { c: '😊', k: 'blush smile happy', cat: 'smileys' },
  { c: '😇', k: 'innocent halo angel', cat: 'smileys' },
  { c: '🙂', k: 'slight smile', cat: 'smileys' },
  { c: '🙃', k: 'upside down', cat: 'smileys' },
  { c: '😉', k: 'wink', cat: 'smileys' },
  { c: '😌', k: 'relieved', cat: 'smileys' },
  { c: '😍', k: 'heart eyes love', cat: 'smileys' },
  { c: '🥰', k: 'smiling hearts', cat: 'smileys' },
  { c: '😘', k: 'kiss heart', cat: 'smileys' },
  { c: '😋', k: 'yum tongue', cat: 'smileys' },
  { c: '😎', k: 'cool sunglasses', cat: 'smileys' },
  { c: '🤓', k: 'nerd glasses', cat: 'smileys' },
  { c: '🥳', k: 'party celebrate', cat: 'smileys' },
  { c: '🤩', k: 'star eyes', cat: 'smileys' },
  { c: '🤔', k: 'thinking', cat: 'smileys' },
  { c: '🙄', k: 'roll eyes', cat: 'smileys' },
  { c: '😏', k: 'smirk', cat: 'smileys' },
  { c: '😴', k: 'sleeping', cat: 'smileys' },
  { c: '😪', k: 'sleepy', cat: 'smileys' },
  { c: '🤐', k: 'zipper mouth', cat: 'smileys' },
  { c: '😬', k: 'grimace', cat: 'smileys' },
  { c: '😶', k: 'no mouth', cat: 'smileys' },
  { c: '🙁', k: 'frown sad', cat: 'smileys' },
  { c: '😣', k: 'persevere', cat: 'smileys' },
  { c: '😢', k: 'cry sad tear', cat: 'smileys' },
  { c: '😭', k: 'sob loud cry', cat: 'smileys' },
  { c: '😡', k: 'angry pouting', cat: 'smileys' },
  { c: '😠', k: 'angry mad', cat: 'smileys' },
  { c: '🤬', k: 'cursing', cat: 'smileys' },
  { c: '😱', k: 'scream fear', cat: 'smileys' },
  { c: '😨', k: 'fearful afraid', cat: 'smileys' },
  { c: '😰', k: 'anxious sweat', cat: 'smileys' },
  { c: '🤒', k: 'sick thermometer', cat: 'smileys' },
  { c: '🤧', k: 'sneezing', cat: 'smileys' },
  { c: '🤮', k: 'vomit', cat: 'smileys' },
  { c: '🤢', k: 'nauseated', cat: 'smileys' },
  { c: '😮', k: 'open mouth surprised wow', cat: 'smileys' },
  // people / hands
  { c: '👋', k: 'wave hi hello', cat: 'people' },
  { c: '🖐', k: 'hand raised', cat: 'people' },
  { c: '✋', k: 'raised hand stop', cat: 'people' },
  { c: '👌', k: 'ok hand', cat: 'people' },
  { c: '🤞', k: 'fingers crossed luck', cat: 'people' },
  { c: '🤟', k: 'love you sign', cat: 'people' },
  { c: '🤘', k: 'rock metal horns', cat: 'people' },
  { c: '✌️', k: 'peace victory', cat: 'people' },
  { c: '👍', k: 'thumbs up like', cat: 'people' },
  { c: '👎', k: 'thumbs down dislike', cat: 'people' },
  { c: '✊', k: 'fist raised', cat: 'people' },
  { c: '👊', k: 'fist bump', cat: 'people' },
  { c: '👏', k: 'clap', cat: 'people' },
  { c: '🙌', k: 'raised hands praise', cat: 'people' },
  { c: '🙏', k: 'pray thanks', cat: 'people' },
  { c: '💪', k: 'flex muscle', cat: 'people' },
  { c: '🫡', k: 'salute', cat: 'people' },
  { c: '❤️', k: 'red heart love', cat: 'people' },
  { c: '🧡', k: 'orange heart', cat: 'people' },
  { c: '💛', k: 'yellow heart', cat: 'people' },
  { c: '💚', k: 'green heart', cat: 'people' },
  { c: '💙', k: 'blue heart', cat: 'people' },
  { c: '💜', k: 'purple heart', cat: 'people' },
  { c: '🖤', k: 'black heart', cat: 'people' },
  { c: '💔', k: 'broken heart', cat: 'people' },
  { c: '💖', k: 'sparkling heart', cat: 'people' },
  { c: '💯', k: '100 hundred', cat: 'people' },
  // nature
  { c: '🐶', k: 'dog', cat: 'nature' },
  { c: '🐱', k: 'cat', cat: 'nature' },
  { c: '🐭', k: 'mouse', cat: 'nature' },
  { c: '🐹', k: 'hamster', cat: 'nature' },
  { c: '🐰', k: 'rabbit bunny', cat: 'nature' },
  { c: '🦊', k: 'fox', cat: 'nature' },
  { c: '🐻', k: 'bear', cat: 'nature' },
  { c: '🐼', k: 'panda', cat: 'nature' },
  { c: '🐨', k: 'koala', cat: 'nature' },
  { c: '🐯', k: 'tiger', cat: 'nature' },
  { c: '🦁', k: 'lion', cat: 'nature' },
  { c: '🐮', k: 'cow', cat: 'nature' },
  { c: '🐷', k: 'pig', cat: 'nature' },
  { c: '🐸', k: 'frog', cat: 'nature' },
  { c: '🐵', k: 'monkey', cat: 'nature' },
  { c: '🐔', k: 'chicken', cat: 'nature' },
  { c: '🐧', k: 'penguin', cat: 'nature' },
  { c: '🐦', k: 'bird', cat: 'nature' },
  { c: '🦆', k: 'duck', cat: 'nature' },
  { c: '🦅', k: 'eagle', cat: 'nature' },
  { c: '🦉', k: 'owl', cat: 'nature' },
  { c: '🐺', k: 'wolf', cat: 'nature' },
  { c: '🐗', k: 'boar', cat: 'nature' },
  { c: '🐴', k: 'horse', cat: 'nature' },
  { c: '🦄', k: 'unicorn', cat: 'nature' },
  { c: '🐝', k: 'bee', cat: 'nature' },
  { c: '🐛', k: 'bug caterpillar', cat: 'nature' },
  { c: '🦋', k: 'butterfly', cat: 'nature' },
  { c: '🐢', k: 'turtle', cat: 'nature' },
  { c: '🐍', k: 'snake', cat: 'nature' },
  { c: '🐙', k: 'octopus', cat: 'nature' },
  { c: '🐳', k: 'whale', cat: 'nature' },
  { c: '🐬', k: 'dolphin', cat: 'nature' },
  { c: '🐟', k: 'fish', cat: 'nature' },
  { c: '🦈', k: 'shark', cat: 'nature' },
  { c: '🐊', k: 'crocodile', cat: 'nature' },
  { c: '🦒', k: 'giraffe', cat: 'nature' },
  { c: '🐘', k: 'elephant', cat: 'nature' },
  { c: '🌳', k: 'tree', cat: 'nature' },
  { c: '🌲', k: 'evergreen tree pine', cat: 'nature' },
  { c: '🌴', k: 'palm tree', cat: 'nature' },
  { c: '🌵', k: 'cactus', cat: 'nature' },
  { c: '🌷', k: 'tulip flower', cat: 'nature' },
  { c: '🌹', k: 'rose flower', cat: 'nature' },
  { c: '🌻', k: 'sunflower', cat: 'nature' },
  { c: '🌼', k: 'blossom flower', cat: 'nature' },
  { c: '🌸', k: 'cherry blossom', cat: 'nature' },
  { c: '🍀', k: 'four leaf clover', cat: 'nature' },
  { c: '🍁', k: 'maple leaf', cat: 'nature' },
  { c: '🌍', k: 'earth globe', cat: 'nature' },
  { c: '☀️', k: 'sun sunny', cat: 'nature' },
  { c: '🌙', k: 'moon crescent', cat: 'nature' },
  { c: '⭐', k: 'star', cat: 'nature' },
  { c: '🌟', k: 'glowing star', cat: 'nature' },
  { c: '⚡', k: 'lightning', cat: 'nature' },
  { c: '🔥', k: 'fire flame', cat: 'nature' },
  { c: '💧', k: 'water droplet', cat: 'nature' },
  { c: '☁️', k: 'cloud', cat: 'nature' },
  { c: '🌧', k: 'rain', cat: 'nature' },
  { c: '❄️', k: 'snow snowflake', cat: 'nature' },
  // food
  { c: '🍎', k: 'red apple', cat: 'food' },
  { c: '🍐', k: 'pear', cat: 'food' },
  { c: '🍊', k: 'orange tangerine', cat: 'food' },
  { c: '🍋', k: 'lemon', cat: 'food' },
  { c: '🍌', k: 'banana', cat: 'food' },
  { c: '🍉', k: 'watermelon', cat: 'food' },
  { c: '🍇', k: 'grapes', cat: 'food' },
  { c: '🍓', k: 'strawberry', cat: 'food' },
  { c: '🫐', k: 'blueberries', cat: 'food' },
  { c: '🍒', k: 'cherries', cat: 'food' },
  { c: '🍑', k: 'peach', cat: 'food' },
  { c: '🥭', k: 'mango', cat: 'food' },
  { c: '🍍', k: 'pineapple', cat: 'food' },
  { c: '🥝', k: 'kiwi', cat: 'food' },
  { c: '🍅', k: 'tomato', cat: 'food' },
  { c: '🥑', k: 'avocado', cat: 'food' },
  { c: '🥦', k: 'broccoli', cat: 'food' },
  { c: '🥒', k: 'cucumber', cat: 'food' },
  { c: '🌶', k: 'hot pepper chili', cat: 'food' },
  { c: '🌽', k: 'corn', cat: 'food' },
  { c: '🥕', k: 'carrot', cat: 'food' },
  { c: '🥐', k: 'croissant', cat: 'food' },
  { c: '🍞', k: 'bread', cat: 'food' },
  { c: '🧀', k: 'cheese', cat: 'food' },
  { c: '🥚', k: 'egg', cat: 'food' },
  { c: '🍳', k: 'fried egg cooking', cat: 'food' },
  { c: '🥓', k: 'bacon', cat: 'food' },
  { c: '🍔', k: 'burger', cat: 'food' },
  { c: '🍟', k: 'fries', cat: 'food' },
  { c: '🍕', k: 'pizza', cat: 'food' },
  { c: '🌭', k: 'hot dog', cat: 'food' },
  { c: '🥪', k: 'sandwich', cat: 'food' },
  { c: '🌮', k: 'taco', cat: 'food' },
  { c: '🌯', k: 'burrito', cat: 'food' },
  { c: '🥙', k: 'falafel pita', cat: 'food' },
  { c: '🥗', k: 'salad', cat: 'food' },
  { c: '🍝', k: 'spaghetti pasta', cat: 'food' },
  { c: '🍜', k: 'noodles ramen', cat: 'food' },
  { c: '🍲', k: 'pot of food', cat: 'food' },
  { c: '🍣', k: 'sushi', cat: 'food' },
  { c: '🍦', k: 'soft ice cream', cat: 'food' },
  { c: '🍩', k: 'doughnut', cat: 'food' },
  { c: '🍪', k: 'cookie', cat: 'food' },
  { c: '🎂', k: 'birthday cake', cat: 'food' },
  { c: '🍰', k: 'shortcake', cat: 'food' },
  { c: '🍫', k: 'chocolate', cat: 'food' },
  { c: '🍬', k: 'candy', cat: 'food' },
  { c: '🍭', k: 'lollipop', cat: 'food' },
  { c: '☕', k: 'coffee', cat: 'food' },
  { c: '🍵', k: 'tea', cat: 'food' },
  { c: '🍶', k: 'sake', cat: 'food' },
  { c: '🍺', k: 'beer', cat: 'food' },
  { c: '🍷', k: 'wine glass', cat: 'food' },
  { c: '🥃', k: 'tumbler whiskey', cat: 'food' },
  { c: '🍸', k: 'cocktail', cat: 'food' },
  // activity
  { c: '⚽', k: 'soccer football', cat: 'activity' },
  { c: '🏀', k: 'basketball', cat: 'activity' },
  { c: '🏈', k: 'american football', cat: 'activity' },
  { c: '⚾', k: 'baseball', cat: 'activity' },
  { c: '🎾', k: 'tennis', cat: 'activity' },
  { c: '🏐', k: 'volleyball', cat: 'activity' },
  { c: '🏉', k: 'rugby', cat: 'activity' },
  { c: '🎱', k: 'pool 8 ball', cat: 'activity' },
  { c: '🏓', k: 'ping pong', cat: 'activity' },
  { c: '🏸', k: 'badminton', cat: 'activity' },
  { c: '🥊', k: 'boxing', cat: 'activity' },
  { c: '🥋', k: 'martial arts', cat: 'activity' },
  { c: '⛳', k: 'golf', cat: 'activity' },
  { c: '🎣', k: 'fishing', cat: 'activity' },
  { c: '🎮', k: 'video game', cat: 'activity' },
  { c: '🎲', k: 'dice game', cat: 'activity' },
  { c: '🎵', k: 'music note', cat: 'activity' },
  { c: '🎶', k: 'music', cat: 'activity' },
  { c: '🎤', k: 'mic karaoke', cat: 'activity' },
  { c: '🎧', k: 'headphones', cat: 'activity' },
  { c: '🎬', k: 'movie clapper', cat: 'activity' },
  { c: '📷', k: 'camera', cat: 'activity' },
  { c: '🎉', k: 'party popper', cat: 'activity' },
  { c: '🎊', k: 'confetti ball', cat: 'activity' },
  { c: '🎁', k: 'gift present', cat: 'activity' },
  { c: '🎈', k: 'balloon', cat: 'activity' },
  { c: '🏆', k: 'trophy', cat: 'activity' },
  { c: '🥇', k: 'gold medal', cat: 'activity' },
  // travel
  { c: '🚗', k: 'car', cat: 'travel' },
  { c: '🚕', k: 'taxi', cat: 'travel' },
  { c: '🚌', k: 'bus', cat: 'travel' },
  { c: '🚓', k: 'police car', cat: 'travel' },
  { c: '🚑', k: 'ambulance', cat: 'travel' },
  { c: '🚒', k: 'fire engine', cat: 'travel' },
  { c: '🚲', k: 'bicycle bike', cat: 'travel' },
  { c: '🛵', k: 'motor scooter', cat: 'travel' },
  { c: '🏍', k: 'motorcycle', cat: 'travel' },
  { c: '🚂', k: 'train', cat: 'travel' },
  { c: '🚆', k: 'train', cat: 'travel' },
  { c: '🚇', k: 'metro', cat: 'travel' },
  { c: '✈️', k: 'plane airplane', cat: 'travel' },
  { c: '🚀', k: 'rocket', cat: 'travel' },
  { c: '🛸', k: 'ufo', cat: 'travel' },
  { c: '⛵', k: 'sailboat', cat: 'travel' },
  { c: '🚢', k: 'ship', cat: 'travel' },
  { c: '🏝', k: 'island', cat: 'travel' },
  { c: '🏔', k: 'mountain', cat: 'travel' },
  { c: '🌅', k: 'sunrise', cat: 'travel' },
  { c: '🌄', k: 'sunrise mountain', cat: 'travel' },
  { c: '🌇', k: 'sunset', cat: 'travel' },
  { c: '🌃', k: 'night stars', cat: 'travel' },
  // objects
  { c: '⌚', k: 'watch time', cat: 'objects' },
  { c: '📱', k: 'phone mobile', cat: 'objects' },
  { c: '💻', k: 'laptop computer', cat: 'objects' },
  { c: '⌨️', k: 'keyboard', cat: 'objects' },
  { c: '🖥', k: 'desktop', cat: 'objects' },
  { c: '🖨', k: 'printer', cat: 'objects' },
  { c: '🖱', k: 'mouse', cat: 'objects' },
  { c: '💾', k: 'floppy disk save', cat: 'objects' },
  { c: '💿', k: 'cd disc', cat: 'objects' },
  { c: '📷', k: 'camera', cat: 'objects' },
  { c: '🔋', k: 'battery', cat: 'objects' },
  { c: '🔌', k: 'plug', cat: 'objects' },
  { c: '💡', k: 'idea light bulb', cat: 'objects' },
  { c: '🔦', k: 'flashlight', cat: 'objects' },
  { c: '📚', k: 'books', cat: 'objects' },
  { c: '📖', k: 'open book', cat: 'objects' },
  { c: '📝', k: 'memo note', cat: 'objects' },
  { c: '🔒', k: 'lock', cat: 'objects' },
  { c: '🔑', k: 'key', cat: 'objects' },
  { c: '🛠', k: 'tools', cat: 'objects' },
  { c: '⏰', k: 'alarm clock', cat: 'objects' },
  { c: '🎂', k: 'cake', cat: 'objects' },
  // symbols
  { c: '✅', k: 'check mark green tick', cat: 'symbols' },
  { c: '❌', k: 'cross x mark', cat: 'symbols' },
  { c: '⭕', k: 'red circle', cat: 'symbols' },
  { c: '✨', k: 'sparkles', cat: 'symbols' },
  { c: '⚠️', k: 'warning', cat: 'symbols' },
  { c: '❗', k: 'exclamation', cat: 'symbols' },
  { c: '❓', k: 'question', cat: 'symbols' },
  { c: '🔔', k: 'bell', cat: 'symbols' },
  { c: '🔕', k: 'no bell mute', cat: 'symbols' },
  { c: '🔇', k: 'muted speaker', cat: 'symbols' },
  { c: '🔊', k: 'loud speaker', cat: 'symbols' },
  { c: '🎯', k: 'target bullseye', cat: 'symbols' },
  { c: '⏳', k: 'hourglass', cat: 'symbols' },
  { c: '⏱', k: 'stopwatch', cat: 'symbols' },
  { c: '🆗', k: 'ok button', cat: 'symbols' },
  { c: '🆕', k: 'new', cat: 'symbols' },
  { c: '🆒', k: 'cool', cat: 'symbols' },
  { c: '🆓', k: 'free', cat: 'symbols' },
];
