#!/usr/bin/env node
// Idempotent pool maintenance for the E2E test suite.
//
// Reads `tests/.env`; for each slot 1..POOL_SIZE either:
//   - probes existing creds by running `configure` against the relay
//     (succeeds = healthy; fails = re-register), or
//   - registers a new chatmail account via `set_config_from_qr` +
//     `configure`, extracts the assigned addr + mail_pw via `get_config`,
//     writes them back to `.env`.
//
// Speaks JSON-RPC over WebSocket to a freshly-spawned `qxp-web` daemon.
// No HTTP to the relay; the daemon owns that surface.
//
// Exit code:
//   0    every slot is healthy (some may have been refreshed)
//   1    one or more slots failed both their existing-creds probe *and*
//        a fresh registration attempt — pool is unsafe to use
//   2    setup error (binary missing, daemon failed to start, etc.)

import { spawn } from 'node:child_process';
import { mkdtemp, rm, readFile, writeFile, rename, stat, access, cp, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { WebSocket } from 'ws';

const __filename = fileURLToPath(import.meta.url);
const TESTS_DIR = path.resolve(path.dirname(__filename), '..');
const REPO_ROOT = path.resolve(TESTS_DIR, '..');
const ENV_PATH = path.join(TESTS_DIR, '.env');
const ENV_EXAMPLE = path.join(TESTS_DIR, '.env.example');

const DAEMON_BINARY = path.join(
  REPO_ROOT,
  'server',
  'target',
  'debug',
  'qxp-web',
);

// ---- env file ----

async function readEnvFile(p) {
  try {
    const text = await readFile(p, 'utf8');
    const out = new Map();
    for (const line of text.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eq = trimmed.indexOf('=');
      if (eq < 0) continue;
      const k = trimmed.slice(0, eq).trim();
      let v = trimmed.slice(eq + 1).trim();
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
        v = v.slice(1, -1);
      }
      out.set(k, v);
    }
    return out;
  } catch (err) {
    if (err.code === 'ENOENT') return new Map();
    throw err;
  }
}

async function writeEnvFile(p, map) {
  // Order: config keys first (in the order .env.example lists them),
  // then a blank line, then the pool slots in numeric order. Anything
  // unrecognised falls through at the end.
  const isSlotKey = (k) => /^QXP_TEST_ACCT_\d+_(EMAIL|PASSWORD)$/.test(k);

  const configOrder = [];
  try {
    const example = await readFile(ENV_EXAMPLE, 'utf8');
    for (const line of example.split('\n')) {
      const m = line.match(/^#?\s*([A-Z_][A-Z0-9_]*)\s*=/);
      if (m && !isSlotKey(m[1])) configOrder.push(m[1]);
    }
  } catch { /* example missing — fall through to map order */ }

  const lines = [];
  lines.push('# E2E pool credentials. Generated by `make test-accounts`. Do not edit by hand.');
  lines.push('# To force a full re-registration: delete this file, then `make test-accounts`.');
  lines.push('');

  const written = new Set();
  for (const k of configOrder) {
    if (map.has(k)) {
      lines.push(`${k}=${quoteIfNeeded(map.get(k))}`);
      written.add(k);
    }
  }
  if (lines.length > 3) lines.push('');

  const slotKeys = [...map.keys()]
    .filter(isSlotKey)
    .sort((a, b) => {
      const na = parseInt(a.match(/_(\d+)_/)[1], 10);
      const nb = parseInt(b.match(/_(\d+)_/)[1], 10);
      if (na !== nb) return na - nb;
      return a.endsWith('EMAIL') ? -1 : 1;
    });
  for (const k of slotKeys) {
    lines.push(`${k}=${quoteIfNeeded(map.get(k))}`);
    written.add(k);
  }

  for (const [k, v] of map.entries()) {
    if (!written.has(k)) lines.push(`${k}=${quoteIfNeeded(v)}`);
  }

  const text = lines.join('\n') + '\n';
  const tmp = `${p}.tmp`;
  await writeFile(tmp, text, 'utf8');
  await rename(tmp, p);
}

function quoteIfNeeded(v) {
  if (v === '') return '';
  if (/[\s#'"`]/.test(v)) return `"${v.replace(/"/g, '\\"')}"`;
  return v;
}

// ---- daemon spawn ----

async function spawnDaemon(accountsDir) {
  await access(DAEMON_BINARY).catch(() => {
    fatal(
      `daemon binary not found at ${DAEMON_BINARY}\n` +
        '  run `make -C server build` (or `cd server && cargo build`) first.',
    );
  });

  const proc = spawn(
    DAEMON_BINARY,
    ['--listen', '127.0.0.1:0', '--accounts-dir', accountsDir],
    { stdio: ['ignore', 'pipe', 'pipe'] },
  );

  let stderrBuf = '';
  proc.stderr.on('data', (chunk) => {
    stderrBuf += chunk.toString();
  });
  proc.stdout.on('data', (chunk) => {
    stderrBuf += chunk.toString();
  });

  // The daemon prints `listening on http://127.0.0.1:<port>` once axum binds.
  // We watch *both* streams since `tracing_subscriber::fmt` defaults to stderr
  // but the running config may have flipped it to stdout.
  const port = await new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      reject(new Error(`daemon did not announce a port within 15s.\nLog so far:\n${stderrBuf}`));
    }, 15_000);
    const check = () => {
      const m = stderrBuf.match(/listening on http:\/\/127\.0\.0\.1:(\d+)/);
      if (m) {
        clearTimeout(timer);
        resolve(parseInt(m[1], 10));
      }
    };
    proc.stderr.on('data', check);
    proc.stdout.on('data', check);
    proc.on('exit', (code) => {
      clearTimeout(timer);
      reject(new Error(`daemon exited prematurely (code=${code}).\nLog:\n${stderrBuf}`));
    });
  });

  return { proc, port };
}

// ---- minimal JSON-RPC over WebSocket client ----

class RpcClient {
  constructor(url) {
    this.url = url;
    this.nextId = 1;
    this.pending = new Map();
    this.ws = null;
  }

  async connect() {
    this.ws = new WebSocket(this.url);
    await new Promise((resolve, reject) => {
      const onOpen = () => {
        this.ws.off('error', onErr);
        resolve();
      };
      const onErr = (err) => {
        this.ws.off('open', onOpen);
        reject(err);
      };
      this.ws.once('open', onOpen);
      this.ws.once('error', onErr);
    });
    this.ws.on('message', (data) => this.handle(data.toString()));
  }

  handle(data) {
    let msg;
    try { msg = JSON.parse(data); } catch { return; }
    if (typeof msg.id !== 'number') return; // ignore notifications (event stream)
    const p = this.pending.get(msg.id);
    if (!p) return;
    this.pending.delete(msg.id);
    if (msg.error) p.reject(new Error(`${msg.error.message} (code ${msg.error.code})`));
    else p.resolve(msg.result);
  }

  call(method, params = []) {
    const id = this.nextId++;
    this.ws.send(JSON.stringify({ jsonrpc: '2.0', id, method, params }));
    return new Promise((resolve, reject) => this.pending.set(id, { resolve, reject }));
  }

  close() {
    try { this.ws?.close(); } catch { /* ignore */ }
  }
}

// ---- pool logic ----

const RELAY_QR = process.env.QXP_TEST_RELAY_QR ?? 'dcaccount:nine.testrun.org';
const POOL_SIZE = parseInt(process.env.QXP_TEST_POOL_SIZE ?? '10', 10);
const DISPLAY_PREFIX = process.env.QXP_TEST_DISPLAY_NAME_PREFIX ?? 'qxp e2e';
// How many pre-paired template pairs to maintain. Each pair consumes 2 pool
// slots. Phase 2+ specs lease a paired template and skip the live
// `secure_join` handshake entirely, which is the single biggest wallclock
// win for the suite. 3 supports up to 3 workers in parallel; tests
// running on worker N consume pair (N mod TEMPLATE_PAIR_COUNT).
const TEMPLATE_PAIR_COUNT = parseInt(process.env.QXP_TEST_TEMPLATE_PAIRS ?? '3', 10);
// Number of trio templates (main + 2 peers, both pre-paired with main).
// Used by the 3 chatlist specs (load-and-sort, pin, search) that need a
// second verified peer to seed two distinct chats. 1 is enough since
// workers=1; bump if/when we run chatlist specs in parallel.
const TEMPLATE_TRIO_COUNT = parseInt(process.env.QXP_TEST_TEMPLATE_TRIOS ?? '1', 10);
const TEMPLATES_DIR = path.join(TESTS_DIR, 'fixtures', 'account-templates');
const MANIFEST_PATH = path.join(TEMPLATES_DIR, 'manifest.json');
const PAIR_TIMEOUT_MS = 180_000;

async function probeSlot(rpc, email, password) {
  const id = await rpc.call('add_account');
  try {
    await rpc.call('set_config', [id, 'addr', email]);
    await rpc.call('set_config', [id, 'mail_pw', password]);
    await rpc.call('configure', [id]);
    return true;
  } catch {
    return false;
  } finally {
    await rpc.call('remove_account', [id]).catch(() => {});
  }
}

async function registerSlot(rpc, n) {
  const id = await rpc.call('add_account');
  try {
    await rpc.call('set_config', [id, 'displayname', `${DISPLAY_PREFIX} ${n}`]);
    await rpc.call('set_config_from_qr', [id, RELAY_QR]);
    await rpc.call('configure', [id]);
    const email = await rpc.call('get_config', [id, 'addr']);
    const password = await rpc.call('get_config', [id, 'mail_pw']);
    if (typeof email !== 'string' || typeof password !== 'string' || !email || !password) {
      throw new Error(`registration returned empty creds (addr="${email}", mail_pw="${password}")`);
    }
    return { email, password };
  } finally {
    await rpc.call('remove_account', [id]).catch(() => {});
  }
}

// ---- pair templates ----

/** Read the templates manifest. Returns { version, templates: [...] } or
 *  a fresh empty manifest if the file is missing/unparseable. */
async function readManifest() {
  try {
    const text = await readFile(MANIFEST_PATH, 'utf8');
    const parsed = JSON.parse(text);
    if (parsed?.version === 1 && Array.isArray(parsed.templates)) return parsed;
  } catch { /* fall through */ }
  return { version: 1, templates: [] };
}

async function writeManifest(manifest) {
  await mkdir(TEMPLATES_DIR, { recursive: true });
  const tmp = `${MANIFEST_PATH}.tmp`;
  await writeFile(tmp, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
  await rename(tmp, MANIFEST_PATH);
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Build one pair template: spin up two daemons, configure each with the
 *  given creds, run a Setup-Contact handshake between them, snapshot
 *  both daemons' accounts dirs to `<templates>/pair-N/{main,peer}`.
 *
 *  Returns the template manifest record. Throws on any failure — the
 *  caller is responsible for retry / abort. */
async function buildPairTemplate(pairId, mainAccount, peerAccount) {
  const mainTmpDir = await mkdtemp(path.join(tmpdir(), `qxp-tpl-${pairId}-main-`));
  const peerTmpDir = await mkdtemp(path.join(tmpdir(), `qxp-tpl-${pairId}-peer-`));

  let mainDaemon, peerDaemon;
  let mainRpc, peerRpc;
  try {
    [mainDaemon, peerDaemon] = await Promise.all([
      spawnDaemon(mainTmpDir),
      spawnDaemon(peerTmpDir),
    ]);
    mainRpc = new RpcClient(`ws://127.0.0.1:${mainDaemon.port}/ws`);
    peerRpc = new RpcClient(`ws://127.0.0.1:${peerDaemon.port}/ws`);
    await Promise.all([mainRpc.connect(), peerRpc.connect()]);

    // Configure each account. Serialised — the chatmail relay sometimes
    // hiccups on simultaneous configure round-trips from the same script,
    // and the wallclock saving from parallelising configure is small
    // compared to the handshake itself.
    async function configure(rpc, account) {
      const id = await rpc.call('add_account');
      await rpc.call('set_config', [id, 'addr', account.email]);
      await rpc.call('set_config', [id, 'mail_pw', account.password]);
      await rpc.call('set_config', [id, 'displayname', `${DISPLAY_PREFIX} ${account.slot}`]);
      // MDN sending must be opt-in on the receiver — default is off.
      // Phase 3+ specs depend on the `OutMdnRcvd` state advancing.
      await rpc.call('set_config', [id, 'mdns_enabled', '1']);
      await rpc.call('configure', [id]);
      await rpc.call('select_account', [id]);
      await rpc.call('start_io', [id]);
      return id;
    }
    const mainAcctId = await configure(mainRpc, mainAccount);
    const peerAcctId = await configure(peerRpc, peerAccount);

    // Settle: give both daemons' IMAP IDLE a beat to actually establish
    // before any pairing traffic flies. In tests this delay happens
    // implicitly (main has been running for seconds during UI login);
    // here we have to wait deliberately or the handshake stalls because
    // neither side is listening.
    await sleep(5_000);

    // Setup-Contact handshake.
    const qr = await mainRpc.call('get_chat_securejoin_qr_code', [mainAcctId, null]);
    const peerChatId = await peerRpc.call('secure_join', [peerAcctId, qr]);

    // Wait for `canSend=true` on peer — that signals it has main's
    // public key and the handshake has reached the final round. Poll
    // every 2s and print progress so a hanging build is debuggable.
    const deadline = Date.now() + PAIR_TIMEOUT_MS;
    let canSend = false;
    let tick = 0;
    while (Date.now() < deadline) {
      const chat = await peerRpc.call('get_full_chat_by_id', [peerAcctId, peerChatId]);
      if (chat.canSend) { canSend = true; break; }
      // Sample peer's chat list and message count every 10s for triage.
      if (tick % 5 === 0) {
        const [peerMsgs, mainChats] = await Promise.all([
          peerRpc.call('get_message_ids', [peerAcctId, peerChatId, false, null]).catch(() => []),
          mainRpc.call('get_chatlist_entries', [mainAcctId, null, null, null]).catch(() => []),
        ]);
        const elapsedSec = Math.floor((Date.now() - (deadline - PAIR_TIMEOUT_MS)) / 1000);
        process.stdout.write(
          `\n    [${elapsedSec}s] peer.canSend=false peer.msgs=${peerMsgs.length} main.chats=${mainChats.length}`,
        );
      }
      tick++;
      await sleep(2000);
    }
    if (!canSend) {
      throw new Error(`pair handshake did not complete within ${PAIR_TIMEOUT_MS / 1000}s`);
    }

    // Give the SMTP queue a beat to flush vc-contact-confirm if it's
    // still in flight, then stop IO so SQLite WAL settles before snapshot.
    await sleep(500);
    await Promise.all([
      mainRpc.call('stop_io', [mainAcctId]).catch(() => {}),
      peerRpc.call('stop_io', [peerAcctId]).catch(() => {}),
    ]);
    await sleep(300);

    return {
      pairId,
      mainSlot: mainAccount.slot,
      peerSlot: peerAccount.slot,
      mainEmail: mainAccount.email,
      peerEmail: peerAccount.email,
      peerPairedChatId: peerChatId,
      createdAt: new Date().toISOString(),
      mainTmpDir,
      peerTmpDir,
    };
  } catch (err) {
    // Best-effort cleanup of tmp dirs on failure.
    await Promise.all([
      rm(mainTmpDir, { recursive: true, force: true }),
      rm(peerTmpDir, { recursive: true, force: true }),
    ]);
    throw err;
  } finally {
    mainRpc?.close();
    peerRpc?.close();
    // Daemons are killed with SIGTERM; give them a moment to flush.
    try { mainDaemon?.proc.kill(); } catch { /* ignore */ }
    try { peerDaemon?.proc.kill(); } catch { /* ignore */ }
    await sleep(300);
  }
}

/** Snapshot `tmpDir` (a live daemon's accounts dir) into `destDir`
 *  under the templates tree. Overwrites any existing snapshot. */
async function snapshotInto(tmpDir, destDir) {
  await rm(destDir, { recursive: true, force: true });
  await mkdir(path.dirname(destDir), { recursive: true });
  await cp(tmpDir, destDir, { recursive: true });
  await rm(tmpDir, { recursive: true, force: true });
}

/** Build one trio template: spin up three daemons, configure each with
 *  the given creds, run Setup-Contact handshakes peer1↔main and
 *  peer2↔main, snapshot all three accounts dirs to
 *  `<templates>/trio-N/{main,peer1,peer2}`.
 *
 *  Returns the trio manifest record. Throws on any failure. */
async function buildTrioTemplate(trioId, mainAccount, peer1Account, peer2Account) {
  const mainTmpDir = await mkdtemp(path.join(tmpdir(), `qxp-tpl-trio-${trioId}-main-`));
  const peer1TmpDir = await mkdtemp(path.join(tmpdir(), `qxp-tpl-trio-${trioId}-peer1-`));
  const peer2TmpDir = await mkdtemp(path.join(tmpdir(), `qxp-tpl-trio-${trioId}-peer2-`));

  let mainDaemon, peer1Daemon, peer2Daemon;
  let mainRpc, peer1Rpc, peer2Rpc;
  try {
    [mainDaemon, peer1Daemon, peer2Daemon] = await Promise.all([
      spawnDaemon(mainTmpDir),
      spawnDaemon(peer1TmpDir),
      spawnDaemon(peer2TmpDir),
    ]);
    mainRpc = new RpcClient(`ws://127.0.0.1:${mainDaemon.port}/ws`);
    peer1Rpc = new RpcClient(`ws://127.0.0.1:${peer1Daemon.port}/ws`);
    peer2Rpc = new RpcClient(`ws://127.0.0.1:${peer2Daemon.port}/ws`);
    await Promise.all([mainRpc.connect(), peer1Rpc.connect(), peer2Rpc.connect()]);

    async function configure(rpc, account) {
      const id = await rpc.call('add_account');
      await rpc.call('set_config', [id, 'addr', account.email]);
      await rpc.call('set_config', [id, 'mail_pw', account.password]);
      await rpc.call('set_config', [id, 'displayname', `${DISPLAY_PREFIX} ${account.slot}`]);
      await rpc.call('set_config', [id, 'mdns_enabled', '1']);
      await rpc.call('configure', [id]);
      await rpc.call('select_account', [id]);
      await rpc.call('start_io', [id]);
      return id;
    }
    const mainAcctId = await configure(mainRpc, mainAccount);
    const peer1AcctId = await configure(peer1Rpc, peer1Account);
    const peer2AcctId = await configure(peer2Rpc, peer2Account);

    await sleep(5_000);

    // Helper: drive one Setup-Contact handshake against main.
    async function pairWithMain(peerRpc, peerAcctId, label) {
      const qr = await mainRpc.call('get_chat_securejoin_qr_code', [mainAcctId, null]);
      const chatId = await peerRpc.call('secure_join', [peerAcctId, qr]);
      const deadline = Date.now() + PAIR_TIMEOUT_MS;
      let tick = 0;
      while (Date.now() < deadline) {
        const chat = await peerRpc.call('get_full_chat_by_id', [peerAcctId, chatId]);
        if (chat.canSend) return chatId;
        if (tick % 5 === 0) {
          const elapsedSec = Math.floor((Date.now() - (deadline - PAIR_TIMEOUT_MS)) / 1000);
          process.stdout.write(`\n    [${elapsedSec}s] ${label}.canSend=false`);
        }
        tick++;
        await sleep(2000);
      }
      throw new Error(`trio handshake (${label}) did not complete within ${PAIR_TIMEOUT_MS / 1000}s`);
    }

    // Serialised handshakes: running them in parallel makes main race
    // its own SMTP queue and the relay sometimes drops the slower side.
    const peer1ChatId = await pairWithMain(peer1Rpc, peer1AcctId, 'peer1');
    const peer2ChatId = await pairWithMain(peer2Rpc, peer2AcctId, 'peer2');

    // Settle longer than the pair template: trio handshakes leave two
    // sets of vc-contact-confirm in flight to main, and main needs to
    // ingest BOTH so its contact table contains both peers before we
    // snapshot it. 500ms was enough for one peer but lost peer2's
    // confirm under load.
    async function mainHasBothPeers() {
      const [p1, p2] = await Promise.all([
        mainRpc.call('lookup_contact_id_by_addr', [mainAcctId, peer1Account.email]),
        mainRpc.call('lookup_contact_id_by_addr', [mainAcctId, peer2Account.email]),
      ]);
      return p1 != null && p2 != null;
    }
    const settleDeadline = Date.now() + 30_000;
    while (Date.now() < settleDeadline) {
      if (await mainHasBothPeers()) break;
      await sleep(1000);
    }
    if (!(await mainHasBothPeers())) {
      throw new Error(
        'trio template build: main did not register both peers as contacts within 30s after handshake',
      );
    }
    // Extra grace so SMTP queue can flush before stop_io.
    await sleep(1000);
    await Promise.all([
      mainRpc.call('stop_io', [mainAcctId]).catch(() => {}),
      peer1Rpc.call('stop_io', [peer1AcctId]).catch(() => {}),
      peer2Rpc.call('stop_io', [peer2AcctId]).catch(() => {}),
    ]);
    await sleep(500);

    return {
      trioId,
      mainSlot: mainAccount.slot,
      peer1Slot: peer1Account.slot,
      peer2Slot: peer2Account.slot,
      mainEmail: mainAccount.email,
      peer1Email: peer1Account.email,
      peer2Email: peer2Account.email,
      peer1PairedChatId: peer1ChatId,
      peer2PairedChatId: peer2ChatId,
      createdAt: new Date().toISOString(),
      mainTmpDir,
      peer1TmpDir,
      peer2TmpDir,
    };
  } catch (err) {
    await Promise.all([
      rm(mainTmpDir, { recursive: true, force: true }),
      rm(peer1TmpDir, { recursive: true, force: true }),
      rm(peer2TmpDir, { recursive: true, force: true }),
    ]);
    throw err;
  } finally {
    mainRpc?.close();
    peer1Rpc?.close();
    peer2Rpc?.close();
    try { mainDaemon?.proc.kill(); } catch { /* ignore */ }
    try { peer1Daemon?.proc.kill(); } catch { /* ignore */ }
    try { peer2Daemon?.proc.kill(); } catch { /* ignore */ }
    await sleep(300);
  }
}

/** Spin up a one-shot daemon against a copy of `mainDir` and assert
 *  both `peer1Email` and `peer2Email` appear in the contact table.
 *  Returns true if both contacts are present, false otherwise. Never
 *  throws — caller treats false as "snapshot is stale, rebuild". */
async function verifyTrioSnapshot(mainDir, _mainEmail, peer1Email, peer2Email) {
  const probeDir = await mkdtemp(path.join(tmpdir(), `qxp-tpl-probe-`));
  let daemon;
  let rpc;
  try {
    await cp(mainDir, probeDir, { recursive: true });
    daemon = await spawnDaemon(probeDir);
    rpc = new RpcClient(`ws://127.0.0.1:${daemon.port}/ws`);
    await rpc.connect();
    const ids = await rpc.call('get_all_account_ids');
    if (!Array.isArray(ids) || ids.length === 0) return false;
    const acctId = ids[0];
    // No need to start_io — `lookup_contact_id_by_addr` is a local DB read.
    const [p1, p2] = await Promise.all([
      rpc.call('lookup_contact_id_by_addr', [acctId, peer1Email]),
      rpc.call('lookup_contact_id_by_addr', [acctId, peer2Email]),
    ]);
    return p1 != null && p2 != null;
  } catch {
    return false;
  } finally {
    rpc?.close();
    try { daemon?.proc.kill(); } catch { /* ignore */ }
    await sleep(200);
    await rm(probeDir, { recursive: true, force: true });
  }
}

/** Bring the trios tree in sync with the pool. Trios live at
 *  `<templates>/trio-K/{main,peer1,peer2}` and consume 3 pool slots each,
 *  starting after the pair-templates. With TEMPLATE_PAIR_COUNT=3 +
 *  TEMPLATE_TRIO_COUNT=1, the slot layout is:
 *    pairs:  1-2, 3-4, 5-6
 *    trios:  7-8-9
 *    free:   10 */
async function ensureTrios(env) {
  const slots = [];
  for (let n = 1; n <= POOL_SIZE; n++) {
    const email = env.get(`QXP_TEST_ACCT_${n}_EMAIL`);
    const password = env.get(`QXP_TEST_ACCT_${n}_PASSWORD`);
    if (!email || !password) continue;
    slots.push({ slot: n, email, password });
  }

  const offset = TEMPLATE_PAIR_COUNT * 2;
  const needed = offset + TEMPLATE_TRIO_COUNT * 3;
  if (slots.length < needed) {
    console.log(
      `trios: pool has ${slots.length} healthy slots; need at least ${needed} ` +
        `for ${TEMPLATE_PAIR_COUNT} pair(s) + ${TEMPLATE_TRIO_COUNT} trio(s). skipping.`,
    );
    return { built: 0, kept: 0, failed: 0 };
  }

  const manifest = await readManifest();
  if (!Array.isArray(manifest.trios)) manifest.trios = [];
  const byTrioId = new Map(manifest.trios.map((t) => [t.trioId, t]));

  let built = 0;
  let kept = 0;
  let failed = 0;

  for (let k = 0; k < TEMPLATE_TRIO_COUNT; k++) {
    const main = slots[offset + k * 3];
    const peer1 = slots[offset + k * 3 + 1];
    const peer2 = slots[offset + k * 3 + 2];
    const existing = byTrioId.get(k);
    const mainDir = path.join(TEMPLATES_DIR, `trio-${k}`, 'main');
    const peer1Dir = path.join(TEMPLATES_DIR, `trio-${k}`, 'peer1');
    const peer2Dir = path.join(TEMPLATES_DIR, `trio-${k}`, 'peer2');

    const dirsPresent = existsSync(mainDir) && existsSync(peer1Dir) && existsSync(peer2Dir);
    const credsMatch =
      existing?.mainEmail === main.email &&
      existing?.peer1Email === peer1.email &&
      existing?.peer2Email === peer2.email;

    if (dirsPresent && credsMatch) {
      // Sanity-check the snapshot: spawn a daemon against a copy of the
      // main dir and verify both peers' addresses landed in the contact
      // table. Earlier builds with too-short settle time produced
      // snapshots where only peer1's vc-contact-confirm had been
      // ingested, leaving peer2 invisible to the picker.
      const ok = await verifyTrioSnapshot(mainDir, main.email, peer1.email, peer2.email);
      if (ok) {
        console.log(`trio ${k}: cached (${main.email} ↔ ${peer1.email} + ${peer2.email})`);
        kept++;
        continue;
      }
      console.log(`trio ${k}: cached snapshot is incomplete (missing peer in main's contacts) — rebuilding`);
    }

    process.stdout.write(`trio ${k}: building ... `);
    try {
      const t = await buildTrioTemplate(k, main, peer1, peer2);
      await snapshotInto(t.mainTmpDir, mainDir);
      await snapshotInto(t.peer1TmpDir, peer1Dir);
      await snapshotInto(t.peer2TmpDir, peer2Dir);
      byTrioId.set(k, {
        trioId: t.trioId,
        mainSlot: t.mainSlot,
        peer1Slot: t.peer1Slot,
        peer2Slot: t.peer2Slot,
        mainEmail: t.mainEmail,
        peer1Email: t.peer1Email,
        peer2Email: t.peer2Email,
        peer1PairedChatId: t.peer1PairedChatId,
        peer2PairedChatId: t.peer2PairedChatId,
        createdAt: t.createdAt,
      });
      console.log('✓');
      built++;
    } catch (err) {
      console.log(`× ${err.message ?? err}`);
      failed++;
    }
  }

  manifest.trios = [...byTrioId.values()].sort((a, b) => a.trioId - b.trioId);
  await writeManifest(manifest);

  return { built, kept, failed };
}

/** Bring the templates tree in sync with the pool. For each pair-slot
 *  0..TEMPLATE_PAIR_COUNT-1, check whether the existing snapshot matches
 *  the current pool creds (mainSlot+peerSlot emails); rebuild any
 *  stale/missing slot.
 *
 *  Pool layout: pair-K uses slots (2K+1, 2K+2). 1+2, 3+4, 5+6, … */
async function ensureTemplates(env) {
  // Gather current creds in the pool. We need pairs 0..N-1.
  const slots = [];
  for (let n = 1; n <= POOL_SIZE; n++) {
    const email = env.get(`QXP_TEST_ACCT_${n}_EMAIL`);
    const password = env.get(`QXP_TEST_ACCT_${n}_PASSWORD`);
    if (!email || !password) continue;
    slots.push({ slot: n, email, password });
  }

  if (slots.length < TEMPLATE_PAIR_COUNT * 2) {
    console.log(
      `templates: pool has ${slots.length} healthy slots; need at least ` +
        `${TEMPLATE_PAIR_COUNT * 2} for ${TEMPLATE_PAIR_COUNT} pairs. ` +
        'skipping template build.',
    );
    return { built: 0, kept: 0, failed: 0 };
  }

  const manifest = await readManifest();
  const byPairId = new Map(manifest.templates.map((t) => [t.pairId, t]));

  let built = 0;
  let kept = 0;
  let failed = 0;

  for (let k = 0; k < TEMPLATE_PAIR_COUNT; k++) {
    const mainAccount = slots[k * 2];
    const peerAccount = slots[k * 2 + 1];
    const existing = byPairId.get(k);
    const mainDir = path.join(TEMPLATES_DIR, `pair-${k}`, 'main');
    const peerDir = path.join(TEMPLATES_DIR, `pair-${k}`, 'peer');

    const dirsPresent = existsSync(mainDir) && existsSync(peerDir);
    const credsMatch =
      existing?.mainEmail === mainAccount.email &&
      existing?.peerEmail === peerAccount.email;

    if (dirsPresent && credsMatch) {
      console.log(`pair ${k}: cached (${mainAccount.email} ↔ ${peerAccount.email})`);
      kept++;
      continue;
    }

    process.stdout.write(`pair ${k}: building ... `);
    try {
      const t = await buildPairTemplate(k, mainAccount, peerAccount);
      await snapshotInto(t.mainTmpDir, mainDir);
      await snapshotInto(t.peerTmpDir, peerDir);
      byPairId.set(k, {
        pairId: t.pairId,
        mainSlot: t.mainSlot,
        peerSlot: t.peerSlot,
        mainEmail: t.mainEmail,
        peerEmail: t.peerEmail,
        peerPairedChatId: t.peerPairedChatId,
        createdAt: t.createdAt,
      });
      console.log('✓');
      built++;
    } catch (err) {
      console.log(`× ${err.message ?? err}`);
      failed++;
    }
  }

  manifest.templates = [...byPairId.values()].sort((a, b) => a.pairId - b.pairId);
  await writeManifest(manifest);

  return { built, kept, failed };
}

// ---- main ----

function fatal(msg, code = 2) {
  console.error(`ensure-pool: ${msg}`);
  process.exit(code);
}

async function main() {
  const env = await readEnvFile(ENV_PATH);

  // Bring up the daemon in a throwaway dir.
  const accountsDir = await mkdtemp(path.join(tmpdir(), 'qxp-pool-init-'));
  let daemon;
  try {
    daemon = await spawnDaemon(accountsDir);
  } catch (err) {
    await rm(accountsDir, { recursive: true, force: true });
    fatal(`could not start qxp-web: ${err.message}`);
  }

  const rpc = new RpcClient(`ws://127.0.0.1:${daemon.port}/ws`);
  try {
    await rpc.connect();
  } catch (err) {
    daemon.proc.kill();
    await rm(accountsDir, { recursive: true, force: true });
    fatal(`could not connect to daemon WebSocket: ${err.message}`);
  }

  let healthy = 0;
  let refreshed = 0;
  let failed = 0;

  try {
    for (let n = 1; n <= POOL_SIZE; n++) {
      const emailKey = `QXP_TEST_ACCT_${n}_EMAIL`;
      const passwordKey = `QXP_TEST_ACCT_${n}_PASSWORD`;
      const email = env.get(emailKey);
      const password = env.get(passwordKey);

      if (email && password) {
        process.stdout.write(`slot ${n}: probing ${email} ... `);
        const ok = await probeSlot(rpc, email, password);
        if (ok) {
          console.log('healthy');
          healthy++;
          continue;
        }
        console.log('dead, re-registering');
      } else {
        process.stdout.write(`slot ${n}: registering ... `);
      }

      try {
        const { email: newEmail, password: newPassword } = await registerSlot(rpc, n);
        env.set(emailKey, newEmail);
        env.set(passwordKey, newPassword);
        console.log(`✓ ${newEmail}`);
        refreshed++;
      } catch (err) {
        console.log(`× ${err.message}`);
        failed++;
      }
    }

    // Persist the effective config values so the .env documents what the
    // pool was created against.
    if (!env.has('QXP_TEST_RELAY_QR')) env.set('QXP_TEST_RELAY_QR', RELAY_QR);
    if (!env.has('QXP_TEST_POOL_SIZE')) env.set('QXP_TEST_POOL_SIZE', String(POOL_SIZE));
    if (!env.has('QXP_TEST_DISPLAY_NAME_PREFIX')) env.set('QXP_TEST_DISPLAY_NAME_PREFIX', DISPLAY_PREFIX);

    await writeEnvFile(ENV_PATH, env);
  } finally {
    rpc.close();
    daemon.proc.kill();
    await rm(accountsDir, { recursive: true, force: true });
  }

  console.log('');
  console.log(`pool summary: ${healthy} healthy, ${refreshed} refreshed, ${failed} failed`);

  if (failed > 0) {
    console.log('templates: skipped — pool has failed slots.');
    process.exit(1);
  }

  // After slot health is good, refresh pair templates. This is what lets
  // Phase 2+ specs skip the per-test 30-90s secure-join handshake.
  console.log('');
  console.log('building pair templates...');
  const tplResult = await ensureTemplates(env);
  console.log(
    `templates: ${tplResult.built} built, ${tplResult.kept} cached, ${tplResult.failed} failed`,
  );

  console.log('');
  console.log('building trio templates...');
  const trioResult = await ensureTrios(env);
  console.log(
    `trios: ${trioResult.built} built, ${trioResult.kept} cached, ${trioResult.failed} failed`,
  );

  process.exit(tplResult.failed + trioResult.failed > 0 ? 1 : 0);
}

main().catch((err) => fatal(err.stack ?? String(err)));
